web:
  image: tid-lab/aggie-test
  links:
    - db
  environment:
    - MONGO_HOST=db
  ports:
    - "80:3000"
db:
  image: mongo:2.6.11
  ports:
     - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
